### ISSUE TITLE
Basculer le champ de date sur le nouveau système de date natif

### ISSUE THREAD

**Issue by franck-tomek** [JcDenis/postExpired#1]
Depuis la version 2.21 de Dotclear, les champs de date sont gérés de façon native html5, et du coup la fonctionnalité pour afficher un calendrier n'est plus active en l'état quand on renseigne la date de péremption dans le plugin. Il faudrait basculer sur un input de type datetime-local (voir sur la date de publication des billets) pour retrouver une fonctionnalité plus user-friendly.

**Comment by JcDenis** [comment]
Normalement fixé avec le dernier commit.
