### ISSUE TITLE
Feature request: change post password on expiry date

### ISSUE THREAD

**Issue by p4bl0-** [JcDenis/postExpired#2]
Hello,

I would like to suggest a new feature: the ability to change the password of a post at the expiry date.

This would allow to have a post scheduled for publication at a given date in the future while having it available already for preview by people knowing the URL and password of the post (currently, scheduled post are offline, so the only way to privately share a post e.g. for proofreading to a few people is to publish it with a password but then one has to manually remove the password and change the post back status to "scheduled").

Thanks :),

**Comment by JcDenis** [comment]
Done, hope it's what you need :)
You can now change or remove a post password at a given date.

**Comment by p4bl0-** [comment]
Wow that was fast! Really cool! I'm testing it in production with a post that should be made public tomorrow at 13:12 and is already accessible right now with a password: https://p4bl0.net/post/2023/05/No-Crypto-Nastasia-Hadjadji :).
I'll see how it goes and report it here :).

**Comment by p4bl0-** [comment]
So it worked alright, the post was indeed accessible without a password at 13:12 today, but it didn't show up publicly on the blog. I guess I should have also set the post status to be set to "published" even thought it was already "published" with a password.

I'm not sure this should be fixed (like automatically set the post to "published" if it had a password and the operation to be done on expiry is to remove the password), because their may be other cases where at the same time the post status should be changed to something else. So it's just something the user should know.

**Comment by JcDenis** [comment]
If a post was already **published** with password, when you _only_ remove the password with the plugin postExpired, the post should stay **published**. Strange it was not the case... I'll do some test but not sure I'll fix this soon.
